name: Deploy WordPress in Container Apps

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: 'Navigate to Workspace'
      run: cd $GITHUB_WORKSPACE

    - name: 'dir just for debug'
      run: |
        dir

    - name: 'Build COntainer Apps'
      shell: pwsh
      run: |
        # env
        $subscriptionId="${{ secrets.SUBSCRIPTIONID }}"
        $ResourceGroup="${{ vars.ResourceGroup }}"
        $location="${{ vars.Location }}"
        $Enviorment="worpress-containerapps"

       
        # Login to Azure
        az login --service-principal -u ${{ secrets.APPLICATIONID }} -p ${{ secrets.SECRET }} --tenant ${{ secrets.TENANTID }}
        
        # Set the subscription context
        az account set --subscription $subscriptionId
        
        # Create a new resource group for the gallery if it doesn't exist
        az group create --name $ResourceGroup --location $location
        
        # Prepare env
        az extension add --name containerapp --upgrade --allow-preview true
        #az extension add --name containerapp-compose --upgrade --yes --allow-preview true
        az provider register --namespace Microsoft.App
        az provider register --namespace Microsoft.OperationalInsights

        # Create Container App Enviorment
        az containerapp env create --name $Enviorment --resource-group $ResourceGroup --location $location

        # Create a container app by explicitly passing in a Compose configuration file.
        az containerapp compose create -g $ResourceGroup --environment $Enviorment --compose-file-path "docker-compose-azure.yml"
